### PR TITLE
Fix nation stats viewer tooltip from only displaying one creator per demon

### LINKED ISSUE #178: Nations Stats Viewer Tooltip doesn't display everyone on levels in the Created section
The api endpoint for a nation's data retrieval only lists one creator under every level, even when there are more than one in total. 

For example [https://pointercrate.com/api/v1/nationalities/US/](https://pointercrate.com/api/v1/nationalities/US/) under created levels and the level Sinister Silence, only solarion is listed as a creator, even though if you were to check the level's creators listed in its demon retrieval endpoint [https://pointercrate.com/api/v2/demons/469/](https://pointercrate.com/api/v2/demons/469/), you would be able to see more US creators such as Magmeta, Doggie, DiamondSplash, Cersia etc.

### PR DESCRIPTION
**Pull request by jasonyess**
Fixed the `created_in` function only retrieving one creator per demon. In the previous SQL statement, every retrieved demon was unique, causing this to happen:
image

Removing the `DISTINCT ON` statement allowed multiple creators of the same demon to be retrieved:
image

Resolves #178 

## License Acceptance

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: pointercrate-demonlist/src/nationality/get.rs [hunk 1]
```diff
@@ -150,7 +150,7 @@ pub async fn unbeaten_in(nation: &Nationality, connection: &mut PgConnection) ->
 }
 
 pub async fn created_in(nation: &Nationality, connection: &mut PgConnection) -> Result<Vec<MiniDemonWithPlayers>> {
-    let mut stream = sqlx::query!( r#"select distinct on (demon) demon, demons.name::text as "demon_name!", demons.position, players.name::text as "player_name!" from creators inner join demons on demons.id=demon inner join players on players.id=creator where nationality=$1"#, nation.iso_country_code).fetch(connection);
+    let mut stream = sqlx::query!( r#"select (demon) demon, demons.name::text as "demon_name!", demons.position, players.name::text as "player_name!" from creators inner join demons on demons.id=demon inner join players on players.id=creator where nationality=$1"#, nation.iso_country_code).fetch(connection);
```
Comment (stadust) [inline pointercrate-demonlist/src/nationality/get.rs:153]:
```suggestion
    let mut stream = sqlx::query!( r#"select demon, demons.name::text as "demon_name!", demons.position, players.name::text as "player_name!" from creators inner join demons on demons.id=demon inner join players on players.id=creator where nationality=$1 order by demon"#, nation.iso_country_code).fetch(connection);
```

**Review by stadust — COMMENTED** [review]
Hi! Thanks for looking into this. No idea why I put a `distinct on` here, maybe a copy-paste error? I think it does need an order by as well though:
